In [145]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [151]:
df = pd.read_csv('homeprices2.csv')
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [155]:
dummies = pd.get_dummies(df.town)
dummies

    monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [157]:
merged = pd.concat([df,dummies], axis='columns')
merged

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [179]:
final = merged.drop(['town'], axis = 'columns')
final

    area   price  monroe township  robinsville  west windsor
0   2600  550000             True        False         False
1   3000  565000             True        False         False
2   3200  610000             True        False         False
3   3600  680000             True        False         False
4   4000  725000             True        False         False
5   2600  585000            False        False          True
6   2800  615000            False        False          True
7   3300  650000            False        False          True
8   3600  710000            False        False          True
9   2600  575000            False         True         False
10  2900  600000            False         True         False
11  3100  620000            False         True         False
12  3600  695000            False         True         False

In [181]:
final_final = final.drop(['west windsor'], axis = 'columns')
final_final

    area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [191]:
x = final_final.drop(['price'], axis = 'columns')
x

    area  monroe township  robinsville
0   2600             True        False
1   3000             True        False
2   3200             True        False
3   3600             True        False
4   4000             True        False
5   2600            False        False
6   2800            False        False
7   3300            False        False
8   3600            False        False
9   2600            False         True
10  2900            False         True
11  3100            False         True
12  3600            False         True

In [193]:
y = final.price

In [195]:
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [203]:
reg = linear_model.LinearRegression()
reg.fit(x,y)

LinearRegression()

In [205]:
reg.intercept_

249790.36766292533

In [219]:
reg.coef_
reg.score(x,y)

0.9573929037221873

In [223]:

test_data = pd.DataFrame([[4000,False, False]], columns = ['area','monroe township', 'robinsville'])
answer = reg.predict(test_data)
print(f'The predicted price for 4000 sqft. home in west windosr is {answer}')

The predicted price for 4000 sqft. home in west windosr is [757380.13330465]